language: c

sudo: required

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - clang-format-6.0
      - splint

compiler:
  - gcc
  - clang

before_install:
  - $CC --version
  - which $CC

  - export CC=`which $CC`

  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update --quiet --assume-yes; fi

script:
- make all