/*ARRAY CREATION*/
#define INITIAL_SIZE 0
#define PADDING_SPACE 0

/*GRAPHIC PRINT*/
#define SPACE_CHAR " "
#define HORIZONTAL_CHAR "═"
#define VERTICAL_CHAR "║"
#define TOP_LEFT_CORNER_CHAR "╔"
#define TOP_RIGHT_CORNER_CHAR "╗"
#define BOTTOM_LEFT_CORNER_CHAR "╚"
#define BOTTOM_RIGHT_CORNER_CHAR "╝"
#define HORIZONTAL_BOTTOM_CENTER_CHAR "╩"
#define HORIZONTAL_TOP_CENTER_CHAR "╦"
#define VERTICAL_RIGHT_CENTER_CHAR "╠"
#define VERTICAL_LEFT_CENTER_CHAR "╣"
#define UNION_CENTER_CHAR "╬"